FROM ubuntu:24.04

# docker build --rm --force-rm --no-cache -f dockerfile.firebase -t firebase .
# docker run -it --rm -p 9005:9005 firebase /bin/bash
RUN TZ=Australia/Melbourne apt-get update \
    && apt-get install -y \
    nodejs \
    node-gyp \
    npm \
    && npm install -g firebase-tools

CMD ["firebase", "help"]
